openapi: 3.0.3
info:
    title: Stock Bot Service
    description: Service for placing and managing stock orders
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /balance:
        get:
            tags:
                - balance
            summary: get balance
            description: Get the account balance summary.
            operationId: balance#get
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StockbotBalance'
                            example:
                                available_cash_for_stock: 0.897048344522705
                                available_margin_for_new_position: 0.9847662144042676
                                has_margin_call: false
                                margin_maintenance_rate: 0.8049012647268458
                                withdrawable_cash: 0.003252871500457864
    /order:
        post:
            tags:
                - order
            summary: create order
            description: Create a new stock order.
            operationId: order#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            is_margin: false
                            order_type: STOP_LIMIT
                            price: 0.6823277361253774
                            quantity: 14045737829345687727
                            symbol: Sit perspiciatis sequi qui id.
                            trade_type: SELL
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                order_id: Cumque quod sint numquam.
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                is_margin:
                    type: boolean
                    description: 信用取引かどうか
                    default: false
                    example: false
                order_type:
                    type: string
                    description: 注文種別 (MARKET/LIMITなど)
                    example: LIMIT
                    enum:
                        - MARKET
                        - LIMIT
                        - STOP
                        - STOP_LIMIT
                price:
                    type: number
                    description: 発注価格 (LIMIT注文の場合)
                    default: 0
                    example: 0.30031297063048695
                    format: double
                quantity:
                    type: integer
                    description: 発注数量
                    example: 6767251228367880624
                    format: int64
                symbol:
                    type: string
                    description: '銘柄コード (例: 7203)'
                    example: Laudantium corrupti omnis dolore at quasi tempore.
                trade_type:
                    type: string
                    description: 売買区分 (BUY/SELL)
                    example: SELL
                    enum:
                        - BUY
                        - SELL
            example:
                is_margin: false
                order_type: STOP_LIMIT
                price: 0.1020377895840843
                quantity: 12321529925262682652
                symbol: Qui cumque voluptatem.
                trade_type: BUY
            required:
                - symbol
                - trade_type
                - order_type
                - quantity
        CreateResponseBody:
            type: object
            properties:
                order_id:
                    type: string
                    description: 受付済み注文ID
                    example: Aliquam maiores aspernatur rerum sequi est.
            description: ID of the created order
            example:
                order_id: Blanditiis voluptatibus dolores quia facilis.
            required:
                - order_id
        StockbotBalance:
            type: object
            properties:
                available_cash_for_stock:
                    type: number
                    description: 現物株式買付可能額
                    example: 0.38514840397707384
                    format: double
                available_margin_for_new_position:
                    type: number
                    description: 信用新規建可能額
                    example: 0.8237833116450515
                    format: double
                has_margin_call:
                    type: boolean
                    description: 追証発生フラグ (1:発生, 0:未発生)
                    example: true
                margin_maintenance_rate:
                    type: number
                    description: 委託保証金率(%)
                    example: 0.2253343121763319
                    format: double
                withdrawable_cash:
                    type: number
                    description: 出金可能額
                    example: 0.01068050672083728
                    format: double
            description: A summary of the account balance.
            example:
                available_cash_for_stock: 0.8531512056629607
                available_margin_for_new_position: 0.9362199561086998
                has_margin_call: false
                margin_maintenance_rate: 0.5889158335579016
                withdrawable_cash: 0.19815970415992543
            required:
                - available_cash_for_stock
                - available_margin_for_new_position
                - margin_maintenance_rate
                - withdrawable_cash
                - has_margin_call
tags:
    - name: order
      description: The order service handles placing stock orders.
    - name: balance
      description: The balance service provides account balance information.
